name: Run pytest tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.7
        poetry_version: 1.0.5
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.7
        poetry_version: 1.0.5
        args: run pytest -v